FROM nginx:1.22
RUN apt-get update -y
RUN apt-get install certbot python3-certbot-nginx -y
RUN apt-get install expect -y
RUN apt-get install vim -y
# COPY nginx.sh .
# RUN certbot certonly --nginx --email za96346@gmail.com --agree-tos -d workapp.tw -n
# COPY . /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf