version: '3.8'

services:
  account_frontend:
    container_name: account_frontend
    image: nginx:1.3
    ports:
      # - "443:443"
      - "80:80"
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: ./frontend/
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      accountNet:
        ipv4_address: 172.21.0.10
    # build: 
    #   context: ./frontend/build/Dockerfile #原路徑
    #   dockerfile: ./frontend/build/Dockerfile #備用路徑

  account_backend:
    container_name: account_backend
    # ports:
    #   - "4000:4000"
    expose:
      - 4500
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: ./backend/
    command: >
      bash -c "npm run start-prod"
    volumes:
    #   - ./volume/logs:/backend/logs
      - ./backend:/backend
    #   - ./backend/.env:/backend/.env
    depends_on:
      - account_mysql
    networks:
      accountNet:
        ipv4_address: 172.21.0.5

  account_mysql:
    image: mysql:8
    container_name: account_mysql
    volumes:
      - ./volume/mysql:/var/lib/mysql
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      MYSQL_ROOT_PASSWORD: siou0722
      # MYSQL_USER: root
      #  MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: accountantSystem
      expose: 3306
    # ports:
    #   - "3306:3306"
    networks:
      accountNet:
        ipv4_address: 172.21.0.2

networks:
  accountNet:
    name: accountNet
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24