FROM node:18
WORKDIR /backend

# COPY . .
# RUN rm -rf go.mod\
#     && go mod init backend\
#     && rm .env\
#     && mv env .env\
#     && go mod tidy\
#     # && go mod download\
#     # && go get ./...
#     && go build -o app .
# EXPOSE 4000
# ENTRYPOINT ./app
# CMD ["go run main.go" ]
