export const donationTransValue = {
    id: '',
    amount: '',
    cycle: '',
    cyclePeriod: '',
    authPeriod: '',
    creditNumber: '',
    creditMaturity: '',
    productName: '',
    consumerName: '',
    consumerTel: '',
    consumerAddr: '',
    consumerEmail: '',
    consumerInvoiceTitle: '',
    consumerInvoiceNumver: '',
    recipientName: '',
    recipientTel: '',
    recipientAddr: '',
    recipientEmail: '',
    notifyUrl: '',
    lastUserEdit: '',
};
